---
title: "Untitled"
format: html
---

```{r}
# norm1 <- 2
# norm2 <- 1
# Z_true_tr <- matrix(exp(rnorm(n * p,mean = norm1,sd = norm2)), ncol = p)
# Z_true_tr <- matrix(exp(rnorm(n * p * 100,mean = norm1,sd = norm2)), ncol = p)
# lod <- exp(qnorm(lod_quantile, mean = norm1, sd = norm2))
# lod <- rep(lod, p)

# Z_obs_tr <- CensorData(Z_true_tr, lod)
# lod_mat <- is.na(Z_obs_tr)
# Z_resp_tr <- log(Z_true_tr)

# Z_obs_plot <- Z_obs_tr
# Z_obs_plot[is.na(Z_obs_plot)] <- lod[1]

# plogis_mean <- 4
# h_true_tr <- 4 * plogis(1/4 * (Z_resp_tr[,1] + Z_resp_tr[,2] + 1/2 * (Z_resp_tr[,1]) * (Z_resp_tr[,2])), location = plogis_mean, scale = 0.5)


# library(ggplot2)
# df <- data.frame(x = log(Z_obs_plot)[,1],y = log(Z_obs_plot)[,2],z = h_true_tr)
# df <- data.frame(x = Z_resp_tr[,1],y = Z_resp_tr[,2],z = h_true_tr)

# ggplot(df, aes(x = x, y = y)) + geom_point(aes(color = z)) + 
#   geom_hline(yintercept = log(lod[1]),colour="red", linetype = "longdash") + 
#   geom_vline(xintercept = log(lod[1]),colour="red", linetype = "longdash")



# var(h_true_tr[(lod_mat[,1] | lod_mat[,2])])
# var(h_true_tr[!(lod_mat[,1] | lod_mat[,2])])

# var(h_true_tr[(lod_mat[,1] | lod_mat[,2])]) / var(h_true_tr)
# var(h_true_tr[(lod_mat[,1] | lod_mat[,2])]) / var(h_true_tr[!(lod_mat[,1] | lod_mat[,2])])

# var(h_true_tr[group_tr > 0])
# var(h_true_tr[group_tr == 0])



###################
library(ggside)

dnorm_shaded <- function(x, lod) {
  y <- dnorm(x, mean = 2, sd = 1)
  y[x > lod] <- NA  # Mask values greater than 2
  return(y)
}

dunif_shaded <- function(x,lod) {
  y <- dunif(x,min = 0, max = 4)
  y[x > lod] <- NA
  return(y)
}

dgamma_shaded <- function(x,lod) {
  y <- dgamma(x, shape = 2, scale = 1)
  y[x > lod] <- NA
  return(y)
}



library(ggplot2)
library(ggside)
library(dplyr)
# library(metR)

# 1. Define the parameters and the Marker Lookup Table
lods <- c(0.25, 0.5, 0.75)
side_colors <- c("#9c179e","#ed7953")

# This table links the facet's LOD value to the specific marker for each distribution
marker_lookup <- data.frame(
  lod_vis = lods,
  m_norm  = qnorm(lods,0,1),
  m_unif  = qunif(lods,-3,3)
#   m_gamma = c(0.9612788, 1.678347, 2.692635)
)

# 2. Create the grid and join the marker values
z1 <- seq(-3, 3, length = 60)
z2 <- seq(-3, 3, length = 60)
locations <- 0 + c(-1, 0, 1)
scales <- c(0.5,1.5)

grid_all <- expand.grid(Z1 = z1, Z2 = z2, loc_val = locations, lod_vis = lods, scales = scales) %>%
  mutate(
    # resp = plogis(eta, location = loc_val, scale = 0.5),
    # resp = plogis((Z1+Z2)/2, location = loc_val, scale = 0.5),
    resp = 0.5 * plogis(Z1, location = loc_val, scale = 1.5) + 0.5 * plogis(Z2, location = loc_val, scale = scales),
    loc_lab = paste("h Center:", loc_val),
    lod_lab = paste("LOD Quantile:", round(lod_vis, 2)),
    scale_lab = paste("Scale:", scales)
  ) %>%
  left_join(marker_lookup, by = "lod_vis") # Adds the specific markers to every row

# 3. Build the plot
ggplot(grid_all, aes(x = Z1, y = Z2, z = resp)) +
    geom_contour_filled(breaks = seq(0, 1, .025)) + 
  

    geom_segment(aes(x = -3, xend = m_norm, y = m_norm, yend = m_norm, linetype  = factor(lod_vis)), color = side_colors[1]) + 
    geom_segment(aes(x = m_norm, xend = m_norm, y = -3, yend = m_norm, linetype  = factor(lod_vis)), color = side_colors[1]) + 

    geom_segment(aes(x = -3, xend = m_unif, y = m_unif, yend = m_unif, linetype  = factor(lod_vis)), color = side_colors[2]) + 
    geom_segment(aes(x = m_unif, xend = m_unif, y = -3, yend = m_unif, linetype  = factor(lod_vis)), color = side_colors[2]) + 
    scale_linetype_manual(values = c("solid", "dashed", "dotted")) + 
  
  facet_grid(loc_lab ~ scale_lab) +
  
  # --- Marginal Functions ---
  geom_xsidefunction(fun = dnorm, args = list(mean = 0, sd = 1), color = side_colors[1], linewidth = 1) + 
  geom_xsidefunction(fun = dunif, args = list(min = -3, max = 3), color = side_colors[2], linewidth = 1) + 
  
  geom_ysidefunction(fun = dnorm, args = list(mean = 0, sd = 1), color = side_colors[1], linewidth = 1) + 
  geom_ysidefunction(fun = dunif, args = list(min = -3, max = 3), color = side_colors[2], linewidth = 1) + 
  

  # --- Distribution Markers (Mapping to the joined columns) ---
  geom_xsidesegment(aes(x = m_norm, xend = m_norm, y = 0, yend = dnorm(m_norm), linetype = factor(lod_vis)), 
                    color = side_colors[1]) +
  geom_xsidesegment(aes(x = m_unif, xend = m_unif, y = 0, yend = 1/6, linetype = factor(lod_vis)), 
                    color = side_colors[2]) +

  geom_ysidesegment(aes(y = m_norm, yend = m_norm, x = 0, xend = dnorm(m_norm)), 
                    color = side_colors[1], linetype = "dashed") +
  geom_ysidesegment(aes(y = m_unif, yend = m_unif, x = 0, xend = 1/6), 
                    color = side_colors[2], linetype = "dashed") +
  

  theme_minimal() + 
  theme_ggside_minimal() + 
  ggside(collapse = "all") + 
  theme(ggside.panel.scale.y = .05,
        ggside.panel.scale.x = .15,
        ggside.axis.text.x = element_blank(), 
        ggside.axis.text.y = element_blank())
        # legend.position = "none")


# ggsave("hCenterLoDdensityUnivar.png",height = 10, width = 10)


```


```{r}
library(ggplot2)
library(ggside)
library(dplyr)

# 1. Define the parameters and the Marker Lookup Table
lods <- c(0.25, 0.5, 0.75)
side_colors <- c("#9c179e","#ed7953")

# This table links the facet's LOD value to the specific marker for each distribution
marker_lookup <- data.frame(
  lod_vis = lods,
  m_norm  = qnorm(lods, 0, 1),
  m_unif  = qunif(lods, -3, 3)
)

# 2. Create the grid and join the marker values
z1 <- seq(-3, 3, length = 60)
z2 <- seq(-3, 3, length = 60)
locations <- 0 + c(-1, 0, 1)
scales <- c(0.5, 1.5)

grid_all <- expand.grid(Z1 = z1, Z2 = z2, loc_val = locations, lod_vis = lods, scales = scales) %>%
  mutate(
    # resp = 0.5 * plogis(Z1, location = loc_val, scale = scales) + 0.5 * plogis(Z2, location = loc_val, scale = scales),
    resp = plogis((Z1+Z2)/2, location = loc_val, scale =scales) ,
    loc_lab = paste("h Center:", loc_val),
    lod_lab = paste("LOD Quantile:", round(lod_vis, 2)),
    scale_lab = paste("Scale:", scales)
  ) %>%
  left_join(marker_lookup, by = "lod_vis") 

# 3. Build the plot
ggplot(grid_all, aes(x = Z1, y = Z2, z = resp)) +
    # --- 1. Continuous Fill for Binned Contours ---
  geom_contour_filled(aes(fill = after_stat(level_mid)), breaks = seq(0, 1, .025)) + 
  scale_fill_viridis_c(name = "Response", breaks = c(0, 0.5, 1), limits = c(0, 1)) +

  # --- Main Plot Segments (color moved inside aes) ---
  geom_segment(aes(x = -3, xend = m_norm, y = m_norm, yend = m_norm, 
                   linetype = factor(lod_vis), color = "Normal"), alpha = 0.05) + 
  geom_segment(aes(x = m_norm, xend = m_norm, y = -3, yend = m_norm, 
                   linetype = factor(lod_vis), color = "Normal"), alpha = 0.05) + 

  geom_segment(aes(x = -3, xend = m_unif, y = m_unif, yend = m_unif, 
                   linetype = factor(lod_vis), color = "Uniform"), alpha = 0.05) + 
  geom_segment(aes(x = m_unif, xend = m_unif, y = -3, yend = m_unif, 
                   linetype = factor(lod_vis), color = "Uniform"), alpha = 0.05) + 
  
  facet_grid(loc_lab ~ scale_lab) +
  
  # --- Marginal Functions (color moved inside aes) ---
  geom_xsidefunction(fun = dnorm, args = list(mean = 0, sd = 1), 
                     aes(color = "Normal"), linewidth = 0.5) + 
  geom_xsidefunction(fun = dunif, args = list(min = -3, max = 3), 
                     aes(color = "Uniform"), linewidth = 0.5) + 
  
  geom_ysidefunction(fun = dnorm, args = list(mean = 0, sd = 1), 
                     aes(color = "Normal"), linewidth = 0.5) + 
  geom_ysidefunction(fun = dunif, args = list(min = -3, max = 3), 
                     aes(color = "Uniform"), linewidth = 0.5) + 

  # --- Distribution Markers (color moved inside aes) ---
  geom_xsidesegment(aes(x = m_norm, xend = m_norm, y = 0, yend = dnorm(m_norm), 
                        linetype = factor(lod_vis), color = "Normal")) +
  geom_xsidesegment(aes(x = m_unif, xend = m_unif, y = 0, yend = 1/6, 
                        linetype = factor(lod_vis), color = "Uniform")) +

  geom_ysidesegment(aes(y = m_norm, yend = m_norm, x = 0, xend = dnorm(m_norm), 
                        linetype = factor(lod_vis), color = "Normal")) +
  geom_ysidesegment(aes(y = m_unif, yend = m_unif, x = 0, xend = 1/6, 
                        linetype = factor(lod_vis), color = "Uniform")) +
  
  # --- 2. Manual Scales for Legends ---
  scale_color_manual(name = "Distribution", 
                     values = c("Normal" = side_colors[1], "Uniform" = side_colors[2])) +
  scale_linetype_manual(name = "LOD Quantile", 
                        values = c("0.25" = "solid", "0.5" = "longdash", "0.75" = "dotted")) +

  theme_minimal() + 
  theme_ggside_minimal() + 
  ggside(collapse = "all") + 
  theme(ggside.axis.text.x = element_blank(), 
        ggside.axis.text.y = element_blank())

ggsave("h3Dens.png")
```

